// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tkcmdiyfriuxiwlwhvgv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRrY21kaXlmcml1eGl3bHdodmd2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDExNTk3NDIsImV4cCI6MjA1NjczNTc0Mn0.j2_xZSgu7m9RZUhH8zmU23--aJtf1quvIPoirlGm0lU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);